// example/src/pages/Features.tsx
import React, { useState, useCallback } from 'react';
import PageLayout from '../components/layout/PageLayout';
import SectionCard from '../components/ui/SectionCard';
import MobileSidebar from '../components/ui/MobileSidebar';
import SidebarNav from '../components/ui/SidebarNav';
import ParticleContainer from '../components/common/ParticleContainer';
import { useMobileSidebar } from '../hooks/useMobileSidebar';
import { scrollToElement } from '../utils';

const sections = [
  { id: 'hook', title: 'Hook 提示注入' },
  { id: 'session', title: 'Session 守护' },
  { id: 'model', title: '多模型路由' },
  { id: 'test', title: '测试凭证' },
];

const Features: React.FC = () => {
  const [activeSection, setActiveSection] = useState('hook');
  const { isOpen, toggle, close } = useMobileSidebar();

  const handleNavClick = useCallback((e: React.MouseEvent, id: string) => {
    e.preventDefault();
    setActiveSection(id);
    scrollToElement(id);
    close();
  }, [close]);

  return (
    <PageLayout>
      <MobileSidebar
        isOpen={isOpen}
        onClose={close}
        onToggle={toggle}
        title="导航"
      >
        <SidebarNav items={sections} activeId={activeSection} onItemClick={handleNavClick} />
      </MobileSidebar>

      {/* Page Header */}
      <div className="mb-8">
        <ParticleContainer
          particleType="heart"
          particleCount={15}
          particleSize={0.6}
          autoTrigger
          triggerDelay={300}
        >
          <h1 className="text-heading-1 text-[var(--text-50)] mb-4 cursor-pointer">功能特性</h1>
        </ParticleContainer>
        <p className="text-body text-[var(--text-400)]">探索 Claude Coder 的核心能力</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
        {/* Desktop Sidebar Navigation */}
        <aside className="hidden lg:block lg:col-span-1">
          <div className="sticky top-24">
            <div className="card p-4 relative overflow-hidden">
              {/* 侧边栏粒子背景 */}
              <ParticleContainer
                particleCount={20}
                particleSize={0.4}
                colors={['var(--primary-500)', 'var(--primary-400)']}
                autoTrigger
                triggerDelay={500}
                className="absolute inset-0 opacity-20 pointer-events-none"
              >
                <div className="w-full h-full" />
              </ParticleContainer>

              <h3 className="text-caption text-[var(--text-400)] uppercase tracking-wider mb-4 relative z-10">功能导航</h3>
              <SidebarNav items={sections} activeId={activeSection} onItemClick={handleNavClick} />
            </div>
          </div>
        </aside>

        {/* Main Content */}
        <div className="lg:col-span-3 space-y-8">
          {/* Hook Injection */}
          <SectionCard id="hook" variant="default" className="card-hover-enhanced">
            <ParticleContainer
              particleType="heart"
              particleCount={12}
              particleSize={0.5}
              colors={['var(--fish-gold)', 'var(--lazy-cyan)']}
              autoTrigger
              triggerDelay={200}
            >
              <h2 className="text-heading-2 text-[var(--text-50)] mb-4 cursor-pointer inline-block">Hook 提示注入机制</h2>
            </ParticleContainer>
            <p className="text-body mb-4 leading-relaxed">
              核心亮点：通过 JSON 配置，在 SDK 工具调用时自动向模型注入上下文引导。
              <strong className="text-[var(--text-50)]">零代码修改</strong>即可扩展 AI 行为规则——
              无需改动源码，只需编辑配置文件就能引导 Agent 遵守编码规范、安全策略。
            </p>
            <div className="code-block-responsive mb-4">
              <pre className="text-[var(--text-200)]">{`{
  "hooks": [
    {
      "trigger": "tool_call",
      "tool": "edit_file",
      "inject": "请确保代码符合项目编码规范"
    }
  ]
}`}</pre>
            </div>
            <p className="text-caption">
              支持三级匹配（全局 / 工具级 / 参数级），可灵活控制注入粒度。
            </p>
          </SectionCard>

          {/* Session Guardian */}
          <SectionCard id="session" variant="default" className="card-hover-enhanced">
            <ParticleContainer
              particleType="heart"
              particleCount={12}
              particleSize={0.5}
              colors={['var(--fish-gold)', 'var(--lazy-cyan)']}
              autoTrigger
              triggerDelay={200}
            >
              <h2 className="text-heading-2 text-[var(--text-50)] mb-4 cursor-pointer inline-block">Session 守护机制</h2>
            </ParticleContainer>
            <p className="text-body mb-4 leading-relaxed">
              专为<strong className="text-[var(--text-50)]">长时间无人值守编码</strong>设计。
              多 Session 编排 + 倒计时活跃度监控，Agent 可连续运行数小时自主完成数十个任务。
            </p>
            <ul className="space-y-3">
              <li className="flex items-start gap-3 animate-slide-in-left" style={{ animationDelay: '0.1s' }}>
                <span className="text-[var(--gradient-start)] mt-0.5">●</span>
                <span className="text-body">自动检测 Session 超时 / 中断，智能恢复上下文</span>
              </li>
              <li className="flex items-start gap-3 animate-slide-in-left" style={{ animationDelay: '0.2s' }}>
                <span className="text-[var(--gradient-start)] mt-0.5">●</span>
                <span className="text-body">倒计时活跃度检测 + 工具运行状态实时追踪</span>
              </li>
              <li className="flex items-start gap-3 animate-slide-in-left" style={{ animationDelay: '0.3s' }}>
                <span className="text-[var(--gradient-start)] mt-0.5">●</span>
                <span className="text-body">失败自动 git 回滚 + 重试，保障代码仓库安全</span>
              </li>
              <li className="flex items-start gap-3 animate-slide-in-left" style={{ animationDelay: '0.4s' }}>
                <span className="text-[var(--gradient-start)] mt-0.5">●</span>
                <span className="text-body">智能防刷屏机制，避免无效循环消耗 Token</span>
              </li>
            </ul>
          </SectionCard>

          {/* Multi-Model Routing */}
          <SectionCard id="model" variant="default" className="card-hover-enhanced">
            <ParticleContainer
              particleType="heart"
              particleCount={12}
              particleSize={0.5}
              colors={['var(--fish-gold)', 'var(--lazy-cyan)']}
              autoTrigger
              triggerDelay={200}
            >
              <h2 className="text-heading-2 text-[var(--text-50)] mb-4 cursor-pointer inline-block">多模型路由</h2>
            </ParticleContainer>
            <p className="text-body mb-4 leading-relaxed">
              不绑定单一模型。支持 Claude 官方、Coding Plan 多模型路由、DeepSeek、GLM-5、Qwen 等
              <strong className="text-[var(--text-50)]">任意 Anthropic 兼容 API</strong>，
              按任务类型灵活分配最优模型，兼顾质量与成本。
            </p>
            <div className="code-block-responsive mb-4">
              <pre className="text-[var(--text-200)]">{`# 推荐配置（长时间自运行最稳）
ANTHROPIC_DEFAULT_OPUS_MODEL=glm-5
ANTHROPIC_DEFAULT_SONNET_MODEL=qwen3-coder-next
ANTHROPIC_DEFAULT_HAIKU_MODEL=qwen3-coder-plus
ANTHROPIC_MODEL=kimi-k2.5`}</pre>
            </div>
          </SectionCard>

          {/* Test Credentials */}
          <SectionCard id="test" variant="default" className="card-hover-enhanced">
            <ParticleContainer
              particleType="heart"
              particleCount={12}
              particleSize={0.5}
              colors={['var(--fish-gold)', 'var(--lazy-cyan)']}
              autoTrigger
              triggerDelay={200}
            >
              <h2 className="text-heading-2 text-[var(--text-50)] mb-4 cursor-pointer inline-block">测试凭证管理</h2>
            </ParticleContainer>
            <p className="text-body mb-4 leading-relaxed">
              Agent 编完代码还能<strong className="text-[var(--text-50)]">自动验证</strong>。
              Playwright 一键导出浏览器登录态，API Key 持久化存储，
              端到端测试全程自动化，交付即可用。
            </p>
            <div className="code-block-responsive">
              <pre className="text-[var(--text-200)]">{`# 一键导出浏览器登录态
claude-coder auth http://localhost:3000

# Agent 测试时自动使用保存的凭证`}</pre>
            </div>
          </SectionCard>
        </div>
      </div>
    </PageLayout>
  );
};

export default Features;

// example/src/pages/Features.vue
<template>
  <div class="min-h-screen">
    <Header />
    <main class="pt-24 pb-20 px-4 sm:px-6 lg:px-8">
      <div class="max-w-7xl mx-auto">
        <h1 class="text-4xl font-bold text-[var(--text-50)] mb-8">功能特性</h1>

        <div class="grid grid-cols-1 lg:grid-cols-4 gap-8">
          <!-- Sidebar Navigation -->
          <aside class="lg:col-span-1">
            <nav class="card sticky top-24">
              <ul class="space-y-2">
                <li v-for="section in sections" :key="section.id">
                  <a :href="`#${section.id}`" class="nav-item" :class="{ active: activeSection === section.id }" @click="activeSection = section.id">
                    {{ section.title }}
                  </a>
                </li>
              </ul>
            </nav>
          </aside>

          <!-- Main Content -->
          <div class="lg:col-span-3 space-y-12">
            <!-- Hook Injection -->
            <section id="hook" class="card">
              <h2 class="text-2xl font-bold text-[var(--text-50)] mb-4">Hook 提示注入机制</h2>
              <p class="text-[var(--text-400)] mb-4">
                通过 JSON 配置在工具调用时向模型注入上下文引导，实现零代码扩展规则。
              </p>
              <div class="code-block mb-4">
                <pre class="text-[var(--text-200)]">{
  "hooks": [
    {
      "trigger": "tool_call",
      "tool": "edit_file",
      "inject": "请确保代码符合项目编码规范"
    }
  ]
}</pre>
              </div>
            </section>

            <!-- Session Guardian -->
            <section id="session" class="card">
              <h2 class="text-2xl font-bold text-[var(--text-50)] mb-4">Session 守护机制</h2>
              <p class="text-[var(--text-400)] mb-4">
                中断策略、倒计时活跃度检测、工具运行状态追踪、防刷屏机制，确保长时间稳定运行。
              </p>
              <ul class="list-disc list-inside text-[var(--text-400)] space-y-2">
                <li>自动检测 Session 超时和中断</li>
                <li>倒计时活跃度检测</li>
                <li>工具运行状态实时追踪</li>
                <li>智能防刷屏机制</li>
              </ul>
            </section>

            <!-- Multi-Model Routing -->
            <section id="model" class="card">
              <h2 class="text-2xl font-bold text-[var(--text-50)] mb-4">多模型路由</h2>
              <p class="text-[var(--text-400)] mb-4">
                支持 Claude 官方、Coding Plan、DeepSeek 等任意 API，灵活配置模型路由。
              </p>
              <div class="code-block mb-4">
                <pre class="text-[var(--text-200)]"># 环境变量配置
ANTHROPIC_DEFAULT_OPUS_MODEL=glm-5
ANTHROPIC_DEFAULT_SONNET_MODEL=qwen3-coder-next
ANTHROPIC_DEFAULT_HAIKU_MODEL=qwen3-coder-plus</pre>
              </div>
            </section>

            <!-- Test Credentials -->
            <section id="test" class="card">
              <h2 class="text-2xl font-bold text-[var(--text-50)] mb-4">测试凭证方案</h2>
              <p class="text-[var(--text-400)] mb-4">
                Playwright 登录态导出、API Key 持久化，安全存储测试凭证。
              </p>
              <div class="code-block">
                <pre class="text-[var(--text-200)]"># 导出浏览器登录态
claude-coder auth http://localhost:3000</pre>
              </div>
            </section>
          </div>
        </div>
      </div>
    </main>
    <Footer />
  </div>
</template>

<script setup>
import { ref } from 'vue'
import Header from '../components/common/Header.vue'
import Footer from '../components/common/Footer.vue'

const sections = [
  { id: 'hook', title: 'Hook 提示注入' },
  { id: 'session', title: 'Session 守护' },
  { id: 'model', title: '多模型路由' },
  { id: 'test', title: '测试凭证' }
]

const activeSection = ref('hook')
</script>

<style scoped>
.nav-item {
  display: block;
  padding: 0.5rem 0.75rem;
  color: var(--text-400);
  border-radius: 0.375rem;
  transition: all 0.2s;
}

.nav-item:hover {
  color: var(--text-50);
  background-color: var(--bg-100);
}

.nav-item.active {
  color: var(--text-50);
  background-color: var(--primary-600);
}
</style>
